# Generated by Django 4.1 on 2022-09-16 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('schools', models.CharField(max_length=70)),
                ('tution_fees', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='Course_image')),
                ('academic_year', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, default='Description should contain course details', max_length=5000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('lectures', models.CharField(blank=True, max_length=30, null=True)),
                ('school_status', models.BooleanField(blank=True, choices=[(0, 'Private'), (1, 'Public')], null=True)),
                ('intake_in', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty', models.CharField(blank=True, max_length=255, null=True)),
                ('course_status', models.BooleanField(blank=True, choices=[(0, 'Government Sponsered'), (1, 'Self Sponsered')], null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=70)),
                ('rated_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Recommender.course')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
