# Generated by Django 4.1 on 2022-09-17 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recommender.course')),
            ],
        ),
    ]
