# Generated by Django 4.1 on 2022-09-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0002_deleted_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleted_course',
            name='title',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
