# Generated by Django 4.1 on 2022-09-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0003_alter_deleted_course_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updated_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('title', models.CharField(default='none', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
