# Generated by Django 4.1 on 2022-09-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0004_updated_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='updated_course',
            name='schools',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
