# Generated by Django 4.1 on 2022-09-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0005_updated_course_schools'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deleted_course',
            old_name='title',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='updated_course',
            old_name='title',
            new_name='course_id',
        ),
        migrations.RemoveField(
            model_name='updated_course',
            name='schools',
        ),
    ]
