# Generated by Django 4.1.3 on 2022-11-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0006_rename_title_deleted_course_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='school_status',
        ),
        migrations.AddField(
            model_name='course',
            name='entry_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='school_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='school_phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
