# Generated by Django 4.1 on 2022-09-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
