# Generated by Django 4.1 on 2022-09-27 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_detail_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='user_detail',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.user_detail')),
            ],
        ),
    ]
