# Generated by Django 4.1 on 2022-09-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_user_detail_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
