# Generated by Django 4.1.3 on 2022-11-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_user_detail_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='password',
        ),
    ]
